name: Discord Notification
description: Utilized for sending Discord Notification

# Inputs
inputs:
  file_name:
    description: "Location of the JSON file"
    required: true
  webhook_url:
    description: "Webhook Url"
    required: true
  repository: 
    description: "Repository"
    required: false
    default: ""
  bot_user_name:
    description: "Name for the Dicord Bot"
    required: false
    default: "Based Tech Bot"
  avatar_url:
    description: "Avatar URL for the Discord Bot"
    required: false
    default: "https://static.wikia.nocookie.net/dragonball/images/6/6e/The_Return_of_Cooler_-_A_new_Meta-Cooler_appears_before_Goku_%26_Vegeta.png/revision/latest?cb=20230626184623"
  image_url:
    description: "Url that displays in the message"
    required: false
    default: ""
  branch_name:
    description: "Current Branch Reference"
    required: true
  trunk_branch_name:
    description: "Trunk Branch"
    required: false
    default: "main"
  current_user:
    description: "Current User"
    required: true
  color:
    description: "Color for the Discord message"
    required: true
  content:
    description: "Content"
    required: false
    default: ""
  sound_url_1:
    description: "Sound Url"
    required: false
    default: ""
  sound_url_2:
    description: "Sound Url 2"
    required: false
    default: ""
  sha_code:
    description: "SHA code"
    required: false
    default: ""
  run_id:
    description: "Run ID"
    required: false
    default: ""
  title:
    description: "Title of notification"
    required: false
    default: ""
  url:
    description: "Url inside of notification"
    required: false
    default: ""



runs:
  using: "composite"
  steps:
     - name: Build Payload JSON
       shell: bash
       env:
        BOT_USER_NAME: ${{inputs.bot_user_name}}
        USER_NAME: ${{inputs.current_user}}
        BRANCH_NAME: ${{inputs.branch_name}}
        SHA: ${{inputs.sha_code}}
        RUN_ID: ${{inputs.run_id}}
        REPOSITORY: ${{inputs.repository}}
        IMAGE_URL: ${{inputs.image_url}}
        COLOR_URL: ${{inputs.color_url}}
        FILE_NAME: ${{inputs.file_name}}
        SOUND_URL_1: ${{inputs.sound_url_1}}
        SOUND_URL_2: ${{inputs.sound_url_2}}
        COLOR: ${{inputs.color}}
        TITLE: ${{inputs.title}}
        URL: ${{inputs.url}}
       run: |
        envsubst < $FILE_NAME > config.json
     
     - name: Validate JSON
       shell: bash
       run: |
          jq . config.json
          cat config.json

     - name: Send Webhook
       shell: bash
       env:
         WEBHOOK_URL: ${{inputs.webhook_url}}
       run: |
         curl -H "Content-Type: application/json" \
               -X POST \
               --data-binary @config.json \
               "$WEBHOOK_URL"
